### ISSUE TITLE
refaire le dégradé vert et rose

### ISSUE THREAD

**Issue by MaudeWilliams** [C2DH/popkult60#20]
Sur la page Home il y a un beau dégradé vert et rose, mais sur les autres pages, c'est plus le vert qui ressort, est ce que l'on peut mettre le même dégradé de couleur pour toutes les pages? Merci!

**Comment by frederic-reis** [comment]
J'ai mis le même fond dégradé avec le moiré sur toutes les pages.
Est-ce que ça convient ?

**Comment by MaudeWilliams** [comment]
C'est parfait merci beaucoup !
