### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by danieleguido** [C2DH/popkult60#5]
- [x] 3 logos per line
- [x] fix links (even on image)
- [x] fix order and get rid of uni.lu logo

**Comment by danieleguido** [comment]
hi @RichardLegay 
can you provide there the missing links? (e.g. for Deutsche Forschungsgemeinschaft, Universität des Saarlandes)

**Comment by RichardLegay** [comment]
Hey, sure thing
DFG http://www.dfg.de/
Uni Saarland https://www.uni-saarland.de/nc/startseite.html

**Comment by RichardLegay** [comment]
I don't think the order matters, so, for me, it's great! Could they be a bit smaller though? Thanks!
